### ISSUE TITLE
S3 key where artifact is uploaded does not match the s3Key SBT property that is returned

### ISSUE THREAD

**Issue by nleeper** [Dwolla/sbt-s3-publisher#11] opened 2018-06-15 20:12 UTC
The S3 keys have two different hashes in the last part of the key before the JAR name. This part of the key is generated by doing a Hash of the artifact file.

**Comment by nleeper** [comment] 2018-06-15 20:37
Example:
Run `sbt -DAWS_ACCOUNT_ID=000000 publish stack/deploy`

Logged out from command:
Published to «s3://<bucket>/lambdas/cloudflare-lambda/9d15d0ce2722d7ec3f1a66546d44cda21e00b623/d88045562d5049c0df6e8ec4cc0ad52ec79a1c82/cloudflare-lambda.jar»

S3Key Cloudformation Parameter value:
lambdas/cloudflare-lambda/9d15d0ce2722d7ec3f1a66546d44cda21e00b623/14dea220256cd12fa3177e3cfffdb634f1ea2311/cloudflare-lambda.jar

The value logged out exists in S3, the value received by Cloudformation does not.

**Comment by bpholt** [comment] 2018-07-25 19:39
I believe this is related to https://github.com/sbt/sbt-assembly/issues/289. If I trigger an initial assembly step prior to publishing, the `s3Key` value remains stable after the publish. 

```
sbt:cloudflare-public-hostname-lambda> ; clean; show stack/parameters; publish; stack/deploy
[success] Total time: 4 s, completed Jul 25, 2018 2:34:31 PM
[info] Updating ...
[info] Done updating.
[info] Compiling 2 Scala sources to /Users/bholt/Developer/CFN/cloudflare-public-hostname-lambda/target/scala-2.12/classes ...
[info] Done compiling.
[info] Strategy 'discard' was applied to 50 files (Run the task at debug level to see details)
[info] Packaging /Users/bholt/Developer/CFN/cloudflare-public-hostname-lambda/target/scala-2.12/cloudflare-public-hostname-lambda-assembly-29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a.jar ...
[info] Done packaging.
[info] * (S3Bucket,dwolla-code-sandbox)
[info] * (S3Key,lambdas/cloudflare-public-hostname-lambda/29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a/4fef2b6570e4f0f747f9a98ebd3e46c4dfb36931/cloudflare-public-hostname-lambda.jar)
[success] Total time: 78 s, completed Jul 25, 2018 2:35:49 PM
[info] Strategy 'discard' was applied to 50 files (Run the task at debug level to see details)
[info] Packaging /Users/bholt/Developer/CFN/cloudflare-public-hostname-lambda/target/scala-2.12/cloudflare-public-hostname-lambda-assembly-29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a.jar ...
[info] Done packaging.
[info] Uploading «cloudflare-public-hostname-lambda-assembly-29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a.jar» to «s3://dwolla-code-sandbox/lambdas/cloudflare-public-hostname-lambda/29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a/da63da6bded33b1e1099012de0ba69133fe28726/cloudflare-public-hostname-lambda.jar»
[info] Published to «s3://dwolla-code-sandbox/lambdas/cloudflare-public-hostname-lambda/29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a/da63da6bded33b1e1099012de0ba69133fe28726/cloudflare-public-hostname-lambda.jar»
[success] Total time: 13 s, completed Jul 25, 2018 2:36:02 PM
[info] Running com.dwolla.cloudformation.cloudflare.CreateTemplate /Users/bholt/Developer/CFN/cloudflare-public-hostname-lambda/stack/target/cloudformation-template.json
[info] Strategy 'discard' was applied to 50 files (Run the task at debug level to see details)
[info] Assembly up to date: /Users/bholt/Developer/CFN/cloudflare-public-hostname-lambda/target/scala-2.12/cloudflare-public-hostname-lambda-assembly-29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a.jar
[success] Total time: 4 s, completed Jul 25, 2018 2:36:06 PM
sbt:cloudflare-public-hostname-lambda> show stack/parameters
[info] Strategy 'discard' was applied to 50 files (Run the task at debug level to see details)
[info] Assembly up to date: /Users/bholt/Developer/CFN/cloudflare-public-hostname-lambda/target/scala-2.12/cloudflare-public-hostname-lambda-assembly-29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a.jar
[info] * (S3Bucket,dwolla-code-sandbox)
[info] * (S3Key,lambdas/cloudflare-public-hostname-lambda/29e0333cf6e4f4e0acae2df46e13b0cd6718bf4a/da63da6bded33b1e1099012de0ba69133fe28726/cloudflare-public-hostname-lambda.jar)
[success] Total time: 3 s, completed Jul 25, 2018 2:37:39 PM
```


In other words, assembly creates a jar with a given hash, then publishing triggers a second jar to be created due to https://github.com/sbt/sbt-assembly/issues/289. Subsequent calls to `s3Key` return the same value as from step 2 due to sbt-assembly output caching kicking in.

**Comment by bpholt** [comment] 2018-07-27 17:08
The root cause of this issue is https://github.com/sbt/util/issues/168, which should be fixed by https://github.com/sbt/util/pull/169. Once that's merged and released, users of this plugin will need to upgrade to the new version of sbt.

In the meantime, the issue can be worked around by adding a preliminary call to `assembly in assembly` before running `publish`.

**Closed as completed by bpholt** 2018-07-27 17:08 UTC
